name: Deploy Lambda Function

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11
      - name: Install dependencies
        run: |
          pip install --target ./package -r requirements.txt
          cd package
          zip -r ../my-deployment-package.zip .
          cd ..
          zip my-deployment-package.zip main.py
          pip install awscli
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} aws s3 my-deployment-package.zip s3://windy-tweet/