name: Deploy Lambda Function

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11
      - name: Generate bundle
        run: |
          pip install --target ./package -r requirements.txt
          cd package
          zip -r ../bundle.zip .
          cd ..
          zip bundle.zip main.py
      - name: Generate Report
        uses: actions/upload-artifact@v2
        with:
          name: main_bundle
          path: ./bundle.zip
          retention-days: 1
      - name: Upload to S3
        uses: shallwefootball/s3-upload-action@master
        id: S3
        with:
          aws_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: us-east-2
          source_dir: ./bundle.zip
